### ISSUE TITLE
Upgrade to Firebase 3 API

### ISSUE THREAD

**Issue by dev-guy** [nyura123/mobx-firebase-store#10]
After doing "npm install firebase" followed by "npm test" the first thing I ran into is this issue:

http://stackoverflow.com/questions/37313536/firebase-uncaught-typeerror-firebase-is-not-a-constructor

There could be more after that.

**Comment by nyura123** [comment]
@dev-guy, thanks for reporting issues!
If you install from devDependencies (#9), it will install the right versions for `npm test`, including firebase@2.4.2.

However Firebase 3 is supported as well, an example is in examples/listAndDetailFirebase3.
