### ISSUE TITLE
Handle Firebase 3.x Auth?

### ISSUE THREAD

**Issue by praneybehl** [nyura123/mobx-firebase-store#11]
Thank you for creating the library is super useful. Has someone used /implemented Firebase 3.x Auth with MobX. The new API provides an observable : 

```
firebase.auth().onAuthStateChanged(function(user) {
  if (user) {
    // User is signed in.
  } else {
    // No user is signed in.
  }
});
```

Just wondering if there is an example on how to effectively implement Firebase Auth with MobX and React(if possible).

Thanks

**Comment by nyura123** [comment]
hi @praneybehl ,
I've added some auth logic to the Firebase3 example, which shows how you can use mobx to display different content based on login status. It's outside the scope of this lib (doesn't need MobxFirebaseStore) but maybe it'll be useful :)

In prod you'd probably need to integrate auth logic into your routing (redirecting on logging in/found auth token, mixing protected/unprotected routes, redirecting on logging out/auth expiration, etc.).

**Comment by praneybehl** [comment]
Thanks mate appreciate it.
Cheers!

**Comment by sakulstra** [comment]
Sorry for bringing this up again. I currently try to use mobx-firebase-store and have some problems with authentication.
How can I ensure that authentication is ready before a subscription is fired?
The code below works when auth is ready, but in some cases it isn't and than firebase tries to subscribe to 'tests/null'. Of course I could just catch the null and don't subscribe in that case, but the allSubs() call won't rerun automatically.

``` js
const allKey = 'allTests';
class TestsStore extends MobxFirebaseStore {
    constructor() {
        super(database.ref());
    }

    all() {
        return this.getData(allKey);
    }

    allSubs() {
        const user = auth.currentUser();
        const userId = user && user.uid;
        return [{
            subKey: allKey,
            asList: true,
            path: `tests/${userId}`,
        }];
    }
}

export default new TestsStore();
```

I'm pretty new to mobx so eventually I'm missing sth and could just add an observer somehow?

Regards,
Lukas

**Comment by nyura123** [comment]
@sakulstra does nyura123/firebase-nest#3 help? Are you using firebase-nest autoSubscriber? Basically if you make your firebase onAuth listener set an observable flag, your component's getSubs can use that flag to return an empty array if flag is false/null (not logged in). 
A caveat when using firebase-nest autoSubscriber is that this flag must also be accessed in the component's render.

**Comment by sakulstra** [comment]
@nyura123 thanks, that helped a lot - anyways I think this library is pretty awesome:+1: and has to earn far more than 28 stars!, but the documentation/examples are a bit sparse :smile: atm.

I'd like to create a simple example with step by step comments and it would be great if you could help pointing out the best practices :)

I'll ping you here as soon as i have sth. presentable ready.

**Comment by nyura123** [comment]
thanks, really appreciate it! Yes, the docs and examples could definitely use an improvement :) There's a fuller chat example in nyura123/firebase-nest-mobx-react (using that HOC instead of autoSubscriber), which might also provide some useful pointers.
