### ISSUE TITLE
How to write/push to Firebase?

### ISSUE THREAD

**Issue by frederickfogerty** [nyura123/mobx-firebase-store#6]
Hey @nyura123. Thanks for the library, it's clear I'm using it from my two pull requests.

I'm still wrapping my head around various things in the API, but one gaping hole keeps emerging. What's the best way to **update** data in Firebase with this library, or does this library just not do that at all? Are we expected to use the firebase API directly? I can see it has loading and subscribing to data sorted, but just can't work out the pushing/updating data part yet.

**Comment by frederickfogerty** [comment]
Ah, I see in your tests you have:

``` js
fb.child('list').set(list);
fb.child('details').set(details);
```

Is the preferred way to update values?

**Comment by nyura123** [comment]
Hi @frederickfogerty, thanks for trying out the lib :)
Yes, the preferred way for now is to just use the raw firebase API directly and
then the updates should automatically show up in the store data.
I will add this to the readme and I'm open to any suggestions to improve this.

**Comment by frederickfogerty** [comment]
In MobX style: `props.store.getData(`users/${user_id}`).name = "Awesome";` would be sick, but I'm happy to settle for the Firebase API for now.

**Comment by frederickfogerty** [comment]
Closing as resolved
