### ISSUE TITLE
Should depend on firebase-nest "^0.0.40" instead of "^0.0.38"

### ISSUE THREAD

**Issue by dev-guy** [nyura123/mobx-firebase-store#7]
I am currently unable to install mobx-firebase-store due to this issue.

**Comment by nyura123** [comment]
hi @dev-guy ,
thanks, I pushed a version that depends on 0.0.40. 

Though I'm confused why 0.0.40 wasn't satisfying ^0.0.38 peer dependency. Also curious, were you just getting an 'unmet peer dependency' warning but still able to run?

**Comment by frederickfogerty** [comment]
Below `1.0.0` semver acts differently, especially in regards to the caret (`^`) operator

http://jubianchi.github.io/semver-check/
http://semver.org/#spec-item-4
https://nodesource.com/blog/semver-tilde-and-caret/

### Below 0.1.0

> Using the caret for versions less than 0.1.0 offers no flexibility at all. Only the exact version specified will be valid.
> 
> For example, ^0.0.3 will only permit only exactly version 0.0.3.

### 0.x.x (i.e. pre 1.0)

> For versions greater than or equal to 0.1.0, but less than 1.0.0, the caret adopts the same behaviour as a tilde and will allow flexibility in patch versions (only).
> 
> For example, ^0.1.3 will permit all versions from 0.1.3 to the next minor, 0.2.0.

**Comment by frederickfogerty** [comment]
I would suggest changing the peer dependency to `>=0.0.38 <0.1.0` until you hit `0.1.0`...

Or just bump to `0.1.0` or `1.0.0`

**Comment by nyura123** [comment]
@frederickfogerty ah, thanks! I'll bump up the version.
