### ISSUE TITLE
Can't run 'npm test' because firebase-nest and mobx aren't installed via "npm install"

### ISSUE THREAD

**Issue by dev-guy** [nyura123/mobx-firebase-store#9]

**Comment by dev-guy** [comment]
Is there a trick to getting npm to use peerDependencies?

**Comment by nyura123** [comment]
@dev-guy, normally `npm install` should install devDependencies. 
If your NODE_ENV  is set to production, you can trying using `npm install --only=dev` (more info is at http://stackoverflow.com/questions/34700610/npm-install-wont-install-devdependencies)

**Comment by dev-guy** [comment]
Hello, mobx and firebase-nest are listed in peerDependencies, not devDependencies.

**Comment by nyura123** [comment]
ah, you're right - added.
